
apiVersion: v1
kind: Namespace
metadata: 
  name: ns-johann-barra
  labels: ns-johann-barra
  app: miapp.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-johann-barra
  namespace: ns-johann-barra
  labels:
    app: miapp.local

spec:
  replicas: 3
  selector:
    matchLabels:
      app: miapp.local
  template:
    metadata:
      labels:
        app: miapp.local
    spec:
      containers:
      - name: tarea-final-johann-barra
        image: johannbarradocker/lab3jbf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: AMBIENTE
            valueFrom:
              configMapKeyRef:
                name: config-johann-barra
                key: AMBIENTE


#        volumeMounts:
#        - name: html-volume
#          mountPath: /usr/share/nginx/html/index.html
#          subPath: index.html

#      volumes:
#      - name: html-volume
#        configMap:
#         name: config-johann-barra

---
apiVersion: v1
kind: Service
metadata:
  name: svc-johann-barra
  namespace: ns-johann-barra
  labels:
    app: miapp.local
spec:
  type: ClusterIP
  selector:
    app: miapp.local
  ports:
  - name: http
    port: 3000
    targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-johann-barra
  namespace: ns-johann-barra
data:
  AMBIENTE:
#    AMBIENTE: desarrollo
  #  AMBIENTE: test
  #  AMBIENTE: produccion

    

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ing-johann-barra
#  namespace: ns-johann-barra
#  labels:
#    app.kubernetes.io/name: miapp.local
#    app: miapp.local
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: miapp.local
#    http:
#      paths:
#      - path: "/"
#        pathType: Prefix
#        backend:
#          service:
#            name: svc-johann-barra
#            port:
#              number: 80
